/* This file is automatically generated according to buzzer.xml */
#include <xinu.h>

devcall buzzerwrite(struct dentry *devptr, char *buffer, int32 count) {

	if(count!=1) {
		return 0;
	}

	unsigned int base_address =  *((unsigned int*)(&devptr->dvcsr));
	int gpio_instance_pin_number = 14;

	GPIO1PinMuxSetup(gpio_instance_pin_number);
	GPIODirModeSet(base_address, gpio_instance_pin_number, GPIO_DIR_OUTPUT);

	kprintf("yoyo");
	if(buffer[0]=='1') {
		GPIOPinWrite(base_address, gpio_instance_pin_number, GPIO_PIN_HIGH);
		return 1;
	}
	else if(buffer[0]=='0') {
		GPIOPinWrite(base_address, gpio_instance_pin_number, GPIO_PIN_LOW);
		return 1;
	}

	return 0;
}
